# This is an exmaple Docker Compose file to start your own Docker Stack

version: '2.3'

networks:
  net:
    driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24
          gateway: 172.27.0.1
        # - subnet: fd00:0:0:0:27::/80
        #   gateway: fd00:0:0:0:27::1

services:

  ####
  # HINT: use only ONE of the example "alexa-fhem:" service
  # definitions below !
  #

  # Minimum example w/o any custom environment variables
  alexa-fhem:
    image: ghcr.io/fhem/fhem/alexa-fhem:2
    restart: always
    networks:
      - net
    ports:
      - "3000:3000"
    volumes:
      - "./alexa-fhem/:/alexa-fhem/"

  # Example w/ custom environment variables
  alexa-fhem:
    image: ghcr.io/fhem/fhem/alexa-fhem:2	
    restart: always
    networks:
      - net
    ports:
      - "3000:3000"
    volumes:
      - "./alexa-fhem/:/alexa-fhem/"
    environment:
      ALEXAFHEM_UID: 6062
      ALEXAFHEM_GID: 6062
      TZ: Europe/Berlin
