name: Build and Test

on:
  push:
    branches:
      - 'master'
      - 'dev*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'dev'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@3.6.0

      - name: Get git vars
        shell: bash
        run: |
          echo "::set-output name=BRANCH::$(echo "${{ env.GITHUB_REF_SLUG }}")"
          echo "::set-output name=IMAGE_VERSION::$( git describe --tags --dirty --match "v[0-9]*")"
        id: gitVars

      - name: prepare some vars
        id: buildVars
        run: |
          VARIANT_IMAGE="${{ steps.gitVars.outputs.IMAGE_VERSION }}-${{ steps.gitVars.outputs.BRANCH }}"
          echo "::set-output name=VARIANT::$(echo "${VARIANT_IMAGE}")"
          echo "::set-output name=VARIANT_IMAGE::$(echo "$VARIANT_IMAGE")"
          echo "::set-output name=BUILD_DATE::$(  date --iso-8601=seconds --utc )"
          # detect rolling branch
          if [[ ${{ steps.gitVars.outputs.BRANCH }} == "master" ]]; then
          echo "::set-output name=TAG_ROLLING::latest"
          else
          echo "::set-output name=TAG_ROLLING::$( echo "${{ steps.gitVars.outputs.BRANCH }}" | tr '[A-Z]' '[a-z]' )"
          fi

      - name: Check variables
        run: |
          echo BRANCH: ${{ steps.gitVars.outputs.BRANCH }}
          echo IMAGE_VERSION: ${{ steps.gitVars.outputs.IMAGE_VERSION }}
          echo VARIANT: ${{ steps.buildVars.outputs.VARIANT }}
          echo VARIANT_IMAGE: ${{ steps.buildVars.outputs.VARIANT_IMAGE }}
          echo BUILD_DATE: ${{ steps.buildVars.outputs.BUILD_DATE }}
          echo ROLLING_TAG: ${{ steps.buildVars.outputs.TAG_ROLLING }}
          
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
             ${{ runner.os }}-build-
             ${{ runner.os }}-buildx-

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fhem/alexa-fhem
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}

      - name: Build for test full blown amd64 
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          load: true  
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ steps.buildVars.outputs.BUILD_DATE }}
            IMAGE_VERSION=${{ steps.buildVars.outputs.VARIANT }}
            IMAGE_VCS_REF=${{ github.sha }}
            ALEXAFHEM_VERSION=0.5.61

      - name: Inspect and run integration tests
        run: |
          docker image inspect ${{ steps.meta.outputs.tags }}
          docker history ${{ steps.meta.outputs.tags }}
          ./scripts/test-integration.sh;

  published_build:
    runs-on: ubuntu-latest
    needs: test_build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@3.6.0

      - name: Get git vars
        shell: bash
        run: |
          echo "::set-output name=IMAGE_VERSION::$( git describe --tags --dirty --match "v[0-9]*")"
          echo "::set-output name=BRANCH::$(echo "${{ env.GITHUB_REF_SLUG }}")"

        id: gitVars


      - name: prepare some vars
        id: buildVars
        run: |
          VARIANT_IMAGE="${{ steps.gitVars.outputs.IMAGE_VERSION }}-${{ steps.gitVars.outputs.BRANCH }}"
          echo "::set-output name=VARIANT::$(echo "${VARIANT_IMAGE}")"
          echo "::set-output name=VARIANT_IMAGE::$(echo "$VARIANT_IMAGE")"
          echo "::set-output name=BUILD_DATE::$(  date --iso-8601=seconds --utc )"
          # detect rolling branch
          if [[ ${{ steps.gitVars.outputs.BRANCH }} == "master" ]]; then
          echo "::set-output name=TAG_ROLLING::latest"
          else
          echo "::set-output name=TAG_ROLLING::$( echo "${{ steps.gitVars.outputs.BRANCH }}" | tr '[A-Z]' '[a-z]' )"
          fi

      - name: Check variables
        run: |
          echo BRANCH: ${{ steps.gitVars.outputs.BRANCH }}
          echo IMAGE_VERSION: ${{ steps.gitVars.outputs.IMAGE_VERSION }}
          echo VARIANT: ${{ steps.buildVars.outputs.VARIANT }}
          echo VARIANT_IMAGE: ${{ steps.buildVars.outputs.VARIANT_IMAGE }}
          echo BUILD_DATE: ${{ steps.buildVars.outputs.BUILD_DATE }}
          echo ROLLING_TAG: ${{ steps.buildVars.outputs.TAG_ROLLING }}
          
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
           ${{ runner.os }}-build-
           ${{ runner.os }}-buildx-

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/fhem/alexa-fhem
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
          
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push cross compiled full blown image on supported platforms
        uses: docker/build-push-action@v2
        with:
          context: .
          load: false  
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ steps.buildVars.outputs.BUILD_DATE }}
            IMAGE_VERSION=${{ steps.buildVars.outputs.VARIANT }}
            IMAGE_VCS_REF=${{ github.sha }}
            ALEXAFHEM_VERSION=0.5.61
